openapi: 3.0.0
info:
  title: Store
  version: '1.0'
  description: 'This is the IntelliGems Store API  '
  contact:
    name: IntelliGems
    email: adam@intelligems.io
servers:
  - url: 'https://dev.intelligems.io'
    description: Dev
paths:
  /store/items:
    get:
      summary: Get Items
      operationId: get-store-items
      parameters:
        - schema:
            type: string
            default: some-user-id
          in: query
          name: userId
          description: User ID for your user to whom we will show the list of items.
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
      description: List items for a user in your store
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
                  currencies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Currency'
              examples:
                Example:
                  value:
                    items:
                      - id: bronze-sword
                        name: Bronze Sword
                        price: 150
                        currencyId: coin
                        visible: true
                      - id: gold-sword
                        name: Gold Sword
                        price: 450
                        currencyId: coin
                        visible: true
                    currencies:
                      - id: coin
                        name: Coin
                        icon: 'https://yourdomain.com/static/img/currency.jpg'
      tags:
        - Mobile API
    parameters: []
  /store/configure/items:
    post:
      summary: Configure Items
      operationId: post-store-configure-items
      responses:
        '200':
          description: OK
      description: Configure items in the store. updated
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'
            examples:
              Example:
                value:
                  items:
                    - id: bronze-sword
                      name: Bronze Sword
                      price: 150
                      currencyId: coin
                      visible: true
                    - id: gold-sword
                      name: Gold Sword
                      price: 450
                      currencyId: coin
                      visible: true
      tags:
        - Configure API
    delete:
      summary: Delete Items
      operationId: delete-store-configure-items
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
        description: ''
      description: Deletes an item from the store.
      tags:
        - Configure API
  /store/configure/currencies:
    post:
      summary: Configure Currencies
      operationId: post-store-configure-currency
      responses:
        '200':
          description: OK
      description: Configure or add a currency
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currencies:
                  $ref: '#/components/schemas/Currency'
            examples:
              Example:
                value:
                  currencies:
                    id: string
                    name: string
                    icon: 'https://yourdomain.com/static/img/currency.jpg'
      tags:
        - Configure API
    delete:
      summary: Delete Currencies
      operationId: delete-store-configure-currency
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      responses:
        '200':
          description: OK
      description: 'Delete a currency. In order to delete, it cannot be referenced by any items.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
        description: ''
      tags:
        - Configure API
    parameters: []
  /store/configure/experiments:
    post:
      summary: Configure Experiments & Variants
      operationId: post-store-configure-experiments
      responses:
        '200':
          description: OK
      description: Add or modify experiments
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                experiments:
                  type: array
                  items:
                    $ref: '#/components/schemas/Experiment'
              required:
                - experiments
            examples:
              Example:
                value:
                  experiments:
                    - id: ab-test-1
                      name: Sword Price Test
                      active: true
                      variants:
                        - name: Lower Prices
                          percentage: 33
                          isControl: false
                          overrides:
                            - itemId: bronze-sword
                              property: price
                              value: 125
                            - itemId: gold-sword
                              property: price
                              value: 425
                        - name: Higher Prices
                          percentage: 33
                          isControl: false
                          overrides:
                            - itemId: bronze-sword
                              property: price
                              value: 175
                            - itemId: gold-sword
                              property: price
                              value: 475
                        - name: Control
                          percentage: 34
                          isControl: true
                          overrides:
                            - itemId: bronze-sword
                              property: price
                              value: 150
                            - itemId: gold-sword
                              property: price
                              value: 450
      tags:
        - Configure API
    delete:
      summary: Delete Experiments
      operationId: delete-store-configure-experiments
      responses:
        '200':
          description: OK
      description: Delete an experiment
      parameters:
        - schema:
            type: string
            default: AUTH_TOKEN
          in: header
          name: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      tags:
        - Configure API
components:
  schemas:
    Item:
      title: Item
      type: object
      x-examples:
        Example Item 1:
          id: bronze-sword
          name: Bronze Sword
          price: 150
          currencyId: coin
          visible: true
        Example Item 2:
          id: gold-sword
          name: Gold Sword
          price: 450
          currencyId: coin
          visible: true
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          description: default price to be listed
        currencyId:
          type: string
          description: currency ID
        visible:
          type: boolean
          description: 'default: true'
      required:
        - id
        - name
        - price
        - visible
      x-tags:
        - Models
    Currency:
      title: Currency
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        icon:
          type: string
          example: 'https://yourdomain.com/static/img/currency.jpg'
      required:
        - id
        - name
      x-examples:
        Example Currency:
          id: coin
          name: Coins
          icon: 'https://yourdomain.com/static/img/currency.jpg'
      x-tags:
        - Models
    Variant:
      title: Variant
      type: object
      properties:
        name:
          type: string
        percentage:
          type: integer
        isControl:
          type: boolean
        overrides:
          type: array
          items:
            type: object
            properties:
              itemId:
                type: string
              property:
                type: string
                enum:
                  - price
                  - name
              value:
                type: string
      x-examples:
        Variant A:
          name: Variant A
          percentage: 33
          isControl: false
          overrides:
            - itemId: bronze-sword
              property: price
              value: 125
      x-tags:
        - Models
      required:
        - name
        - percentage
    Experiment:
      title: Experiment
      type: object
      x-tags:
        - Models
      properties:
        id:
          type: string
        name:
          type: string
        active:
          type: boolean
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'
      x-examples:
        Example AB Test:
          id: ab-test-1
          name: Sword Price Test
          active: true
          variants:
            - name: Lower Prices
              percentage: 33
              isControl: false
              overrides:
                - itemId: bronze-sword
                  property: price
                  value: 125
                - itemId: gold-sword
                  property: price
                  value: 425
            - name: Higher Prices
              percentage: 33
              isControl: false
              overrides:
                - itemId: bronze-sword
                  property: price
                  value: 175
                - itemId: gold-sword
                  property: price
                  value: 475
            - name: Control
              percentage: 34
              isControl: true
              overrides:
                - itemId: bronze-sword
                  property: price
                  value: 150
                - itemId: gold-sword
                  property: price
                  value: 450
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: ''
security:
  - Authorization: []
tags:
  - name: Configure API
  - name: Mobile API
