openapi: 3.0.0
info:
  title: Store
  version: '1.0'
  description: 'This is the IntelliGems Store API  '
servers:
  - url: 'https://dev.intelligems.io'
    description: Dev
paths:
  /store/items:
    get:
      summary: Get Items
      tags: []
      operationId: get-store-items
      parameters:
        - schema:
            type: string
            default: some-user-id
          in: query
          name: userId
          description: User ID for your user to whom we will show the list of items.
          required: true
      description: ''
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: ''
security:
  - Authorization: []
